# Generated by Django 4.2.4 on 2024-04-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='games',
            field=models.IntegerField(verbose_name='Игры'),
        ),
        migrations.AlterField(
            model_name='players',
            name='goals',
            field=models.IntegerField(verbose_name='Голы'),
        ),
        migrations.AlterField(
            model_name='players',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
    ]
