# Generated by Django 4.2.4 on 2024-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_players_games_alter_players_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
